config/routes.rb
Rails.application.routes.draw do


  get 'welcomes/index'

  get 'welcomes/about'

  get 'welcomes/workshops'

  root 'welcomes#index'
  get 'about', to: 'welcomes#about'
  get 'workshops', to: 'welcomes#workshops'

  get 'basque', to: 'trips#basque'
  get 'berlin', to: 'trips#berlin'
  get 'marseille', to: 'trips#marseille'
  get 'bali', to: 'trips#bali'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def berlin
  end

  def basque
  end

  def marseille

  end

  def bali
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end

  def about
  end

  def workshops
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travelogue - Women Travel Groups</title>
    <%= csrf_meta_tags %>
     <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar-wagon">
    <!-- Logo -->
    <a href="/" class="navbar-wagon-brand">
      <%= cl_image_tag("TRAVELOGUE-LOGO-INLINE-COLOR_cvsiks.png") %>
    </a>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to 'About', about_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to 'Events', workshops_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to 'Blog', 'https://medium.com/travelogue-co', class: "navbar-wagon-item navbar-wagon-link" %>

    <div class="navbar-wagon-item dropdown-link">
      <div class="dropdown">
        <%= link_to '#', class:"navbar-wagon-link dropdown-toggle", id:'navbar-wagon-menu', 'data-toggle':"dropdown" do %>
          Trips <i class="fa fa-angle-double-down"></i>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Just relax retreat in Provence", marseille_path %></li>
          <li><%= link_to "Bali Oceanlove retreat", bali_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
    <%= yield %>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
<%= link_to 'https://www.instagram.com/travelogue.co/', target: "_blank", class:"social-buttons" do %>
      <i class="fa fa-instagram fa-3x" aria-hidden="true"></i>
    <% end %>
<%= link_to 'https://www.facebook.com/travelogue.co/', target: "_blank", class:"social-buttons" do %>
      <i class="fa fa-facebook fa-3x" aria-hidden="true"></i>
    <% end %>
<p class="footer-links"><%= link_to 'Home', root_path %> | <%= link_to 'About Travelogue', about_path  %> | <%= link_to 'Workshops & Events', workshops_path  %> | <%= link_to 'Marseille Retreat', marseille_path %> </p>
<p>Want to know more about Travelogue? Drop us a <%= mail_to 'hana@travelogue.com', "line", class:"mail-link" %>.</p>
</div>

app/views/trips/bali.html.erb
<div class="basques-page">
  <div class="banner carousel-color">
    <div class="carousel event-carousel slide" id="baliCarousel" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#baliCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#baliCarousel" data-slide-to="1"></li>
        <li data-target="#baliCarousel" data-slide-to="2"></li>
        <li data-target="#baliCarousel" data-slide-to="3"></li>
        <li data-target="#baliCarousel" data-slide-to="4"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
            <%= cl_image_tag "BaliRetreat2016_-3811_n911qq" %>
        </div>
        <div class="item">
            <%= cl_image_tag "BaliRetreat2016_-4091_xhp37z" %>
        </div>
        <div class="item">
            <%= cl_image_tag "BaliRetreat2016_-4826_p7sq8c" %>
        </div>
         <div class="item">
            <%= cl_image_tag "BaliRetreat2016_-4320_bjbcxs" %>
        </div>
        <div class="item">
            <%= cl_image_tag "BaliRetreat2016_-5306_nxuxon" %>
        </div>
        <!-- <a class="carousel-control-prev" href="#baliCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#baliCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a> -->
      </div>


    </div>
    <div class="retreat-center">
      <h1 class="cover">Bali Oceanlove Retreat</h1>
    </div>
  </div>

</div>

<ul class="flex-container basques-content">
  <li class="flex-item-1">
    <div class="retreat-information">
      <h1>Bali Oceanlove Retreat</h1>
      <h2>February 17–27, 2018 | €1451 - €1626 </h2>
      <p>You've got 10 days to travel with ten other women. Some may be strangers but after a few days, you'll become a traveling tribe.</p>
      <p>We all catch ourselves doing it: dreaming about sun, beaches, surfing, relaxing while being stuck at the office and it’s grey and cold outside. We admit to doing it too. That’s where a Travelogue retreat comes in handy! So get ready for our next edition: we decided to partner up with Seasoul Collective for an exclusive Balinese surf and yoga retreat.</p>
      <p>This trip will be what winter vacation dreams are made of luxurious accommodation, daily yoga, fun surf lessons, workshops and cultural experiences.</p>
      <p>For ten days you will share with other passionate female travelers an amazing villa located Canggu a perfect spot near the most beautiful beaches, where you will be able to bond and share your life experiences in an idyllic decor.</p>
      <p>You will be able to participate in Yoga sessions to rest your mind from your stressful everyday life, learn or just practice surfing to energize your hibernating body.</p>
      <p>For beginners or those who are confident in catching a green wave, we offer professional surf guided sessions, customized on your individual level.</p>
      <p>Finally, imbue yourself with the beauty of the Balinese landscapes. You will have the chance to hang out with locals and get a taste of the oh-so-famous chilled and relaxed Bali lifestyle.</p>
      <p>Enjoy 10 days of bliss at our tranquil Villa in Canggu, with surf, yoga, healthy food, cultural tours, professional photography and more…</p>
      <p>You love traveling? You want to learn something new? Discover a new culture? And relax?</p>
      <p>€1451 in a double room with an ensuite bathroom shared with your best friend</p>
      <p>€1626 in a double private room with ensuite bathroom</p>
      <p>For more info, send us an email at   <%= mail_to "hana@travelogue.co", "hana@travelogue.co" %>.</p>
    </div>
    <div class="accomodations">
    <h1>Accomodations</h1>
    <div class="carousel event-carousel slide" id="houseCarousel" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#houseCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#houseCarousel" data-slide-to="1"></li>
        <li data-target="#houseCarousel" data-slide-to="2"></li>
        <li data-target="#houseCarousel" data-slide-to="3"></li>
        <li data-target="#houseCarousel" data-slide-to="4"></li>
        <li data-target="#houseCarousel" data-slide-to="5"></li>
        <li data-target="#houseCarousel" data-slide-to="6"></li>
        <li data-target="#houseCarousel" data-slide-to="7"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
            <%= cl_image_tag "11bce6e6_original_i0n340" %>
        </div>
        <div class="item">
            <%= cl_image_tag "65e6a7ba_original_ihw2wp" %>
        </div>
        <div class="item">
            <%= cl_image_tag "8fe2fd6c-f063-4de5-bf6b-31973d6ec3d1_c9efmf" %>
        </div>
         <div class="item">
            <%= cl_image_tag "9bda8979-d47c-4c39-9d06-58e0fd0d273a_vpxc44" %>
        </div>
        <div class="item">
            <%= cl_image_tag "0f3070e9-f3fa-4d69-9740-1e3edd121fbe_rrhihw" %>
        </div>
        <div class="item">
            <%= cl_image_tag "1fbb955c_original_iukvl9" %>
        </div>
        <div class="item">
            <%= cl_image_tag "2d35bb51-546a-423a-80b5-d39716a86404_trkl1x" %>
        </div>
        <div class="item">
            <%= cl_image_tag "0a175bc6_original_cn1ett" %>
        </div>
      </div>
      <a class="carousel-control-prev" href="#houseCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#houseCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
      </div>
  </li>
  <li class="flex-item">
    <h2>Retreat Schedule</h2>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Day 1</h3>
      </div>
        <div class="panel-body">Arrival during the day and welcome dinner at the house (included in price)</div>
        <div class="panel-heading">
          <h3 class="panel-title">Day 2</h3>
        </div>
        <div class="panel-body">Our awesome, Ale, will prepare with love a breakfast every morning for you. We will have surf sessions and for stretching your muscles, you will be able to participate in yoga classes.
For the evening, dinners are not included. You will have the opportunity to try delicious restaurants in Canggu or just cook some comfort food at home.</div>
        <div class="panel-heading">
          <h3 class="panel-title">Day 3</h3>
        </div>
        <div class="panel-body">Our awesome Ale will prepare with love a breakfast every morning for you. We will have surf sessions and for stretching your muscles, you will be able to participate in yoga classes.
For the evening, dinners are not included. You will have the opportunity to try delicious restaurants in Canggu or just cook some comfort food at home.</div>
        <div class="panel-heading">
          <h3 class="panel-title">Day 4</h3>
        </div>
        <div class="panel-body">Our awesome Ale will prepare with love a breakfast every morning for you. We will have surf sessions and for stretching your muscles, you will be able to participate in yoga classes.
For the evening, dinners are not included. You will have the opportunity to try delicious restaurants in Canggu or just cook some comfort food at home.</div>
        <div class="panel-heading">
          <h3 class="panel-title">Day 5</h3>
        </div>
        <div class="panel-body">Surf Trip/Boat Trip. Breakfast included with water, fruits and other snacks for the road included. Lunch at the beach aftersurf (not incl). Dinner at home (around) or in the spot if wanted, or cook yourself. </div>
        <div class="panel-heading">
          <h3 class="panel-title">Day 6</h3>
        </div>
        <div class="panel-body">Our awesome Ale will prepare with love a breakfast every morning for you. We will have surf sessions and for stretching your muscles, you will be able to participate in yoga classes.
For the evening, dinners are not included. You will have the opportunity to try delicious restaurants in Canggu or just cook some comfort food at home.</div>
        <div class="panel-heading">
          <h3 class="panel-title">Day 7</h3>
        </div>
        <div class="panel-body">Cultural Trip and fun at Uluwatu. Breakfast included with water, fruits and other snacks for the road included. Lunch at the beach aftersurf (not incl). Dinner at home (around) or in the spot if wanted, or cook yourself. </div>
        <div class="panel-heading">
          <h3 class="panel-title">Day 8</h3>
        </div>
        <div class="panel-body">Our awesome Ale will prepare with love a breakfast every morning for you. We will have surf sessions and for stretching your muscles, you will be able to participate in yoga classes.
For the evening, dinners are not included. You will have the opportunity to try delicious restaurants in Canggu or just cook some comfort food at home.</div>
        <div class="panel-heading">
          <h3 class="panel-title">Day 9</h3>
        </div>
        <div class="panel-body">Cultural Trip & Shopping in Ubud. Breakfast included with water, fruits and other snacks for the road included. Lunch at the beach aftersurf (not incl). Dinner at home (around) or in the spot if wanted, or cook yourself. </div>
        <div class="panel-heading">
          <h3 class="panel-title">Day 10</h3>
        </div>
        <div class="panel-body">Surf trip. Breakfast included with water, fruits and other snacks for the road included. Lunch at the beach aftersurf (not incl). Dinner at home (around) or in the spot if wanted, or cook yourself.</div>
        <div class="panel-heading">
          <h3 class="panel-title">Day 11</h3>
        </div>
        <div class="panel-body">Departure. Leave rooms by 12.00pm.</div>
      </div>
    </div>
  </li>

</ul>

app/views/trips/basque.html.haml
%div.basques-page

  %div.banner.carousel-color

    .carousel.event-carousel.slide{:id=>"basqueCarousel", :data => {:ride => "carousel"}}
      %ol.carousel-indicators
        %li.active{:data => {:target => "basqueCarousel", :slide_to => "0"}}
        %li{:data => {:target => "basqueCarousel", :slide_to => "1"}}
        %li{:data => {:target => "basqueCarousel", :slide_to => "2"}}
        %li{:data => {:target => "basqueCarousel", :slide_to => "3"}}


      .carousel-inner
        .item.active
          = cl_image_tag "bordeaux_fh1v1g", :alt => ""
        .item
          = cl_image_tag "women_surfer_n4qwuh", :alt => ""
        .item
          = cl_image_tag "women_surfer2_dguv6s", :alt => ""
        .item
          = cl_image_tag "pays-basque_i27mjw", :alt => ""
      %a.left.carousel-control{:href => "#basqueCarousel", :role => "button", :data => {:slide => "prev"}}
        %span.glyphicon.glyphicon-chevron-left
        %span.sr-only Previous
      %a.right.carousel-control{:href => "#basqueCarousel", :data => {:slide => "next"}}
        %span.glyphicon.glyphicon-chevron-right
        %span.sr-only Next

    %div.banner-content.retreat-center
      %h1.cover Retreat in the French Basque
      %h3.cover One last chance to celebrate summer to the fullest
      %a.btn.btn-primary.community-button{"data-target" => "#basquesModal", "data-toggle" => "modal", :type => "button"}
        Apply to Join!
      %div#basquesModal.modal.fade{"aria-labelledby" => "basquesModalLabel", :role => "dialog", :tabindex => "-1"}
        %div.modal-dialog{:role => "document"}
          %div.modal-content
            %div.modal-body
              %div.typeform-widget{"data-url" => "https://travelogue1.typeform.com/to/hwK5Bt", :style => "width: 100%; height: 500px;"}
              = content_for :javascript do
                %script
                  (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })()

              %div{:style => "font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;"}
                powered by
                %a{:href => "https://www.typeform.com/examples/?utm_campaign=hwK5Bt&utm_source=typeform.com-9436401-Basic&utm_medium=typeform&utm_content=typeform-embedded-poweredbytypeform&utm_term=EN", :style => "color: #999", :target => "_blank"} Typeform



            %div.modal-footer
              %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close


%ul.flex-container.basques-content
  %li.flex-item-1
    %h1 Surf Retreat to Basque Country
    %h2 September 20-25, 2017 | ~ €600
    %p You've got six days to travel with six other women. Some may be strangers but after a few days, you'll become a traveling tribe.
    %p You'll land in Bordeaux where you'll explore the city as a local, practice your French, dive into the food culture and do your best to get a little lost.
    %p From there, you'll head to Hendaye near the border of Spain. Hendaye is a surfer paradise in the Southwest of France that has a little Spanish flavor.
    %p Over the next few days you'll learn how to surf from a man named Laurent, relax on the beach and practice your yoga moves.
    %p When you've finally triumphed hopping onto a surfboard, you'll venture to Saint-Jean-de-Luz, the darling of Basques country! Here the positivity from learning something new will continue to flow like the French wine you'll surely be sipping on.
    %p As all great things end, you'll head back to Bordeaux or wherever you are off to next wrapping up a memorable trip with memorable women.
    %p Please email for a fixed price based upon room choice.
    %p= link_to "For more details visit here!", "https://www.dropbox.com/s/og3rpdhks5w9u8y/Surf-retreat-program-final.pdf?dl=0", :target => "_blank"


  %li.flex-item
    %h2 Retreat Schedule
    %div.panel.panel-default
      %div.panel-heading
        %h3.panel-title Day 1
      %div.panel-body Leave Berlin and fly to Bordeaux. From there, we'll hope on a train to Hendaye to enjoy some relaxation and a nice dinner.
      %div.panel-heading
        %h3.panel-title Day 2
      %div.panel-body In Hendaye, we'll rise early to start surf lessons and enjoy some time to sit on the beach, do some yoga and explore Hendaye. In the afternoon, we'll toast one another during a wine tour.
      %div.panel-heading
        %h3.panel-title Day 3
      %div.panel-body Wake up early for the second surf lesson. Then it's a day trip to Saint Jean de Luz.
      %div.panel-heading
        %h3.panel-title Day 4
      %div.panel-body One last surfing lesson before we head to Spain for Tapas. After we get back, we'll head to Bordeux to finish up our travels.
      %div.panel-heading
        %h3.panel-title Day 5
      %div.panel-body An entire day to adventure around Bordeaux.
      %div.panel-heading
        %h3.panel-title Day 6
      %div.panel-body Head to the airport early to go home.

app/views/trips/marseille.html.haml
%div.basques-page

  %div.banner.carousel-color

    .carousel.event-carousel.slide{:id=>"retreatCarousel", :data => {:ride => "carousel"}}
      %ol.carousel-indicators
        %li.active{:data => {:target => "retreatCarousel", :slide_to => "0"}}
        %li{:data => {:target => "retreatCarousel", :slide_to => "1"}}
        %li{:data => {:target => "retreatCarousel", :slide_to => "2"}}
        %li{:data => {:target => "retreatCarousel", :slide_to => "3"}}
        %li{:data => {:target => "retreatCarousel", :slide_to => "4"}}

      .carousel-inner
        .item.active
          = cl_image_tag "marseille-seaside_i9wo9c", :alt => ""
        .item
          = cl_image_tag "beach-yoga_f4rzgg", :alt => ""
        .item
          = cl_image_tag "shawnee-wilborn-54431_mem0lz", :alt => ""
        .item
          = cl_image_tag "marseille-port_ocivi6", :alt => ""
        .item
          = cl_image_tag "land-water_p55xxn", :alt => ""
      / %a.left.carousel-control{:href => "#retreatCarousel", :role => "button", :data => {:slide => "prev"}}
      /   %span.glyphicon.glyphicon-chevron-left
      /   %span.sr-only Previous
      / %a.right.carousel-control{:href => "#retreatCarousel", :data => {:slide => "next"}}
      /   %span.glyphicon.glyphicon-chevron-right
      /   %span.sr-only Next


    %div.retreat-center
      %h1.cover{:style => "padding-top:70px;"} Just Relax Retreat in Provence France
      / %h3.cover Relax, Rewind and Raw Cosmetic Creation
      / %a.btn.btn-primary.community-button{"data-target" => "#basquesModal", "data-toggle" => "modal", :type => "button"}
      /   Apply to Join!
      / %div#basquesModal.modal.fade{"aria-labelledby" => "basquesModalLabel", :role => "dialog", :tabindex => "-1"}
      /   %div.modal-dialog{:role => "document"}
      /     %div.modal-content
      /       %div.modal-body
      /         %div.typeform-widget{"data-url" => "https://travelogue1.typeform.com/to/hwK5Bt", :style => "width: 100%; height: 500px;"}
      /         = content_for :javascript do
      /           (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })()
      /         %div{:style => "font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;"}
      /           powered by
      /           %a{:href => "https://www.typeform.com/examples/?utm_campaign=hwK5Bt&utm_source=typeform.com-9436401-Basic&utm_medium=typeform&utm_content=typeform-embedded-poweredbytypeform&utm_term=EN", :style => "color: #999", :target => "_blank"} Typeform


      /       %div.modal-footer
      /         %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close



%ul.flex-container.basques-content
  %li.flex-item-1
    %div.retreat-information
      %h1 Just Relax Retreat in Provence France
      %h2 November 16-19, 2017 | ~ €500
      %p You’ve got four days to travel with six other women. Some may be strangers but after a few days, you’ll become a traveling tribe.
      %p Marseille--shaped by an intersection of mountains, forests, the Mediterranean sea and old school ports--is the oldest city in France making it truly the French OG.
      %p You'll land in Marseille on Saturday and go straight to a beautiful house in Auriol. It's in the middle of the mountains and forest, yet still a stone's throw from the sea.
      %p November is a beautiful time to enjoy the south of France with way fewer tourists and a tad less heat.
      %p Our host will be Cécile, an amazing woman who will teach us yoga, meditation, and massage to learn how to relax and handle being in shape while still being on the grind in our everyday lives
      %p Valérie will host a workshop around natural cosmetics so you can walk away knowing how to create your own.
      %p Also, one day we'll spend time in Marseille seaside, go visit Vallon des Auffes or discover more food and culture in the city limits.
      %p It's going to be all about food, relaxation, swimming and natural cosmetics products, essentials oils, plants & DIY for you travel lovers.
      %p Email #{mail_to "hana@travelogue.co", "hana@travelogue.co"} for more information.

      %p= link_to "For more details visit here!", "https://www.dropbox.com/s/tqfxw3yv2o2jd8y/relax-rewind-cosmetic-retreat-program.pdf?dl=0", :target => "_blank"

  %li.flex-item
    %h2 Retreat Schedule
    %div.panel.panel-default
      %div.panel-heading
        %h3.panel-title Day 1
      %div.panel-body Arrive in Auriol. Appéro and drinks will follow in the evening.
      %div.panel-heading
        %h3.panel-title Day 2
      %div.panel-body Day trip to Cassis and Marseille where we will explore. Followed by welcome drinks with the speakers, then yoga and meditation with Alex. Finally, more appéro and drinks!
      %div.panel-heading
        %h3.panel-title Day 3
      %div.panel-body Early yoga with Alex. Then you have the choice to walk through the mountains or learn about Ayuverdic cooking with Alex. Next, we brunch! Afterwards you can find your dosha and diet according to your lifestyle with Alex, then, one-on-one massages with Florence. Wait, there's still more. We'll have a class on essential oils and how to create your own moisturizer with Caroline. Once again, there will be apéro and dinner.
      %div.panel-heading
        %h3.panel-title Day 4
      %div.panel-body Our last day will be filled with yoga and meditation, then one-on-one massages and naturopathic counseling with Florence. Afterwards you can create your own deodorant and toothpaste with Florence before we depart.

app/views/welcomes/about.html.haml
%div.row.about
  %h1 ABOUT
  %h3 Travelogue connects women looking to explore.

%div.about-section
  .about-information
    .row.about-one
      .col-md-4.about_photo
        %img{:src => asset_path("hana.jpg"), :class => "img-rounded hana"}
      .col-md-8.about-info
        %h2 Hana Hrz
        %h3 Founder & CEO
        %ul.links.list-unstyled
          %li
            = mail_to 'hana@travelogue.com' do
              %icons.fa.fa-envelope-o
              Email
          %li
            = link_to 'https://www.instagram.com/hanahrz/' do
              %icons.fa.fa-instagram
              Instagram
        %p Hana's as zesty and spunky as the cities she's lived in: Shanghai, Berlin, Paris and Madrid. From organizing tech conferences to building communities, Hana is all about bringing people together. What's her end goal you may ask?
        %p Seeing more women hit the road and gaining more confidence while doing so.
        %p She spends all her money on travel, wine, cheese and baguettes.Lots and lots of baguettes.
        And voiláá, you have kind of, sort of met Hana.


    .row.about-two
      .col-md-4.about_photo
        %img{:src => asset_path("erinn.jpg"), :class => "img-rounded erinn"}
      .col-md-8.about-info
        %h2 Erinn Springer
        %h3 Cofounder
        %ul.links.list-unstyled
          %li
            = mail_to 'erinnlspringer@gmail.com' do
              %icons.fa.fa-envelope-o
              Email
          %li
            = link_to 'https://www.instagram.com/erinnlspringer/' do
              %icons.fa.fa-instagram
              Instagram
        %p About six years ago, Erinn quit her job, learned how to code and got a remote gig. While it's not clear which of these was the gateway drug to living out of a bag, soon Erinn became a digital nomad. After some time she's traveled a bit and lives in Berlin.
        %p Expect a mix of fun, sass and ambivert-ness from her. She doesn't believe in putting down roots or doing things in heels, but won't judge you for doing the same.